name: Showcase Act

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
        description: Name to greet

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet input
        run: echo "Hello ${{ inputs.name }}"

      - name: Secrets
        run: echo "${{ secrets.best_framework }} is the best frontend framework trust me"

      - name: Show secret
        run: |
          echo ${{ secrets.best_framework }} | sed 's/./& /g'
